document_name: 0.97
buyer_name: 0.99
buyer_address: 0.99
buyer_tax_id: 0.99
buyer_branch_code: 0.99
buyer_branch_name: 0.99
vendor_name: 0.98
vendor_address: 0.98
vendor_tax_id: 0.99
vendor_branch_code: 0.99
vendor_branch_name: 0.99
tax_invoice_number: 0.99
tax_invoice_date: 0.99
total_amount: 0.98
vat: 0.98
net_amount: 0.98
copy: 1.00
receiver_signature: 1.00
withholding_tax: 0.98
invoice_number: 0.99
invoice_amount: 0.98
vat_invoice: 0.99
stamp: 1.00
