repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.txt$
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: check-yaml
        exclude: ^cloud_build/.*\.yaml$
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
