# Project identification
# sonar.projectKey=sqp_f5f19270d9b77007bc497612d3bd4d1ab71339b1
sonar.projectName=RTR-FRAUD-VALIDATION
sonar.projectVersion=1.0

# Source code location
sonar.sources=app

# Python specific settings
sonar.language=py
sonar.python.version=3.8,3.9,3.10,3.11

# Coverage report path
sonar.python.coverage.reportPaths=coverage-reports/coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions (optional - adjust as needed)
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/venv/**,**/.venv/**